### ISSUE TITLE
Analytics Tab is Not Robust to Lack of Data

### ISSUE THREAD

**Issue by kashev** [daranguiz/barbell-io#33]
Repro Steps:
1. Create Account
2. Enter a single lift (didn't put RPE, not sure if related)
3. Click the analytics tab:

```
Traceback (most recent call last):
  File "/home/kashev/.virtualenvs/barbell-io/lib/python3.5/site-packages/tornado/web.py", line 1446, in _execute
    result = self.prepare()
  File "/home/kashev/.virtualenvs/barbell-io/lib/python3.5/site-packages/tornado/web.py", line 2706, in prepare
    self.fallback(self.request)
  File "/home/kashev/.virtualenvs/barbell-io/lib/python3.5/site-packages/livereload/server.py", line 113, in __call__
    WSGIContainer.environ(request), start_response)
  File "/home/kashev/.virtualenvs/barbell-io/lib/python3.5/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/kashev/.virtualenvs/barbell-io/lib/python3.5/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kashev/.virtualenvs/barbell-io/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/kashev/.virtualenvs/barbell-io/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kashev/.virtualenvs/barbell-io/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kashev/.virtualenvs/barbell-io/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kashev/.virtualenvs/barbell-io/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/kashev/.virtualenvs/barbell-io/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kashev/.virtualenvs/barbell-io/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kashev/.virtualenvs/barbell-io/lib/python3.5/site-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/mnt/windows/Users/Kashev/Dropbox/dev/barbell-io/app/views.py", line 185, in user_analytics
    if (cur_max > maxes[week_idx]):
IndexError: list index out of range
```

**Comment by bradysalz** [comment]
Probably related to #28
